name: learn-github-actions
run-name: Run ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v2
  
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get keystore
        run: echo ${{ secrets.KEYSTORE }} | base64 --decode > android/app/teste.keystore
      - name: Get properties
        run: echo ${{ secrets.KEYPROPERTIES }} | base64 --decode > android/key.properties
      - name:  Print properties
        run: echo ${{ secrets.KEYPROPERTIES }} && cat android/key.properties && ls .

      - name: Run Flutter pub get
        run: flutter pub get

      - name: Run Flutter build
        run: flutter build apk
      
      - name: Archive the build
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/apk/release/app-release.apk



  
      


  