name: learn-github-actions
run-name: Run ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v2
  
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Run Flutter pub get
        run: flutter pub get

      - name: Run Flutter build
        run: flutter build apk
      
      - name: Archive the build
        uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: build/app/outputs/flutter-apk

  

  
      


  