name: learn-github-actions
run-name: Run ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - main

jobs:
  build_android:

    runs-on: ubuntu-latest
    environment: 
      name: teste
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Get Repository
        uses: actions/checkout@v2
  
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get keystore
        env:
          KEYPROPERTIES: ${{ secrets.KEYPROPERTIES }}
          KEYSTORE: ${{ secrets.KEYSTORE }}
          teste: "teste"


        run: |
          echo "$KEYSTORE" | base64 --decode > android/app/teste.keystore
          echo "$KEYPROPERTIES" | base64 --decode > android/key.properties

      - name: "Retrieve version"
        id: version
        run: |
          echo "OLD_VERSION=$(cat ${GITHUB_WORKSPACE}/pubspec.yaml | grep 'version:' | head -1 | cut -f2- -d: | sed -e 's/^[ \t]*//')" >> $GITHUB_OUTPUT
          echo "NEW_VERSION=$(awk '{ match($0,/([0-9]+)\+([0-9]+)/,a); a[1]=a[1]+1; a[2]=a[2]+1; sub(/[0-9]+\+[0-9]+/,a[1]"+"a[2])}1' ${GITHUB_WORKSPACE}/pubspec.yaml | grep 'version:' | head -1 | cut -f2- -d: | sed -e 's/^[ \t]*//')" >> $GITHUB_OUTPUT
      - name: "Increment version"
        run: |
          sed -i 's/${{ steps.version.outputs.OLD_VERSION }}/${{ steps.version.outputs.NEW_VERSION }}/g' ${GITHUB_WORKSPACE}/pubspec.yaml
          echo ${{ steps.version.outputs.OLD_VERSION }}
          echo ${{ steps.version.outputs.NEW_VERSION }}
      - name: "Commit version"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Bump version to ${{ steps.version.outputs.NEW_VERSION }}"
          commit_options: '--no-verify'
          commit_user_name: "EdsonMello-code"
          commit_user_email: "edsonmelo754@gmail.com"
          file_pattern: "pubspec.yaml"

      - name: Create new tag
        uses: anothrNick/github-tag-action@v1
        with:
          tag: ${{ steps.version.outputs.NEW_VERSION }}
          message: 'New version ${{ steps.version.outputs.NEW_VERSION }}'
          CUSTOM_TAG: 'v${{ steps.version.outputs.NEW_VERSION }}'
          

      # - name: Run Flutter pub get
      #   run: flutter pub get

      # - name: Run Flutter build
      #   run: flutter build apk
      
      # - name: Archive the build
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: android-build
      #     path: build/app/outputs/apk/release/app-release.apk

      # - name: Upload store google  
      #   env:
      #     GOOGLE_PLAY_CREDENTIALS_JSON: ${{ secrets.GOOGLE_PLAY_CREDENTIALS_JSON }}
      #   run: |
      #     echo "$GOOGLE_PLAY_CREDENTIALS_JSON" | base64 --decode > android/google_api_key.json
      #     cd android
      #     fastlane deploy

         


  
      


  
# name: learn-github-actions
# run-name: Run ${{ github.actor }} is learning GitHub Actions
# on: 
#   push:
#     branches:
#       - main

# jobs:
#   build_android:
  
#     runs-on: ubuntu-latest
#     environment: 
#       name: teste
#     steps:
#       - name: Get Repository
#         uses: actions/checkout@v2
  
#       - name: Setup Flutter SDK
#         uses: subosito/flutter-action@v2
#         with:
#           channel: stable
#       - name: Get keystore
#         env:
#           KEYPROPERTIES: ${{ secrets.KEYPROPERTIES }}
#           KEYSTORE: ${{ secrets.KEYSTORE }}
#           teste: "teste"


#         run:  echo "nossa keystore $KEYSTORE e $KEYPROPERTIES e $teste"
#           # echo "$KEYSTORE" | base64 --decode > android/app/teste.keystore
#           # echo "$KEYPROPERTIES" | base64 --decode > android/key.properties
#           # cat android/key.properties
#           # ls .

         


#       - name: Run Flutter pub get
#         run: flutter pub get

#       - name: Run Flutter build
#         run: flutter build apk
      
#       - name: Archive the build
#         uses: actions/upload-artifact@v4
#         with:
#           name: android-build
#           path: build/app/outputs/apk/release/app-release.apk



  
      


  